name: Weather Data Script

on:
  schedule:
    - cron: 10 14 * * *
  workflow_dispatch:

jobs:
  run-weather-script:
    runs-on: ubuntu-latest  

    steps:
      - name: Trigger Code Checkout
        uses: actions/checkout@v3

      - name: Run weather.sh script
        run: ./weather.sh
