name: Weather Data Script

on:
    schedule:
      - cron: 25 14 * * *
    workflow_dispatch:   

jobs:
    run-weather-script:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Run weather.sh script
          run: ./weather.sh
