name: Weather Data Script

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:   

permissions:
  contents: write  # This is the MVP of the entire file

jobs:
  run-weather-script:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Configure Git Identity
        run: |
          git config --global user.email "ciangall1@gmail.com"
          git config --global user.name "Cian Gallagher"

      - name: Run weather.sh script
        run: ./weather.sh
  
      - name: Add file
        run: git add .

      - name: Commit file
        run: git commit -m "Automated file commit $(date +"%Y%m%d_%H%M%S")"

      - name: Push file
        run: git push

